# Generated by Django 3.0.4 on 2020-04-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.IntegerField(default=666666666)),
                ('dir', models.CharField(max_length=150)),
                ('f_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('f_adquisicion', models.DateField()),
                ('f_intalacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('cof', models.CharField(max_length=75)),
                ('cp', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=75)),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
                ('empleados', models.ManyToManyField(to='appProduccion.Empleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduccion.Equipo')),
            ],
        ),
    ]
