# Generated by Django 3.0.4 on 2020-04-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='f_adquisicion',
            new_name='fecha_adquisicion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='f_intalacion',
            new_name='fecha_instalacion',
        ),
    ]
