# Generated by Django 3.0.4 on 2020-04-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0002_auto_20200409_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='dir',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='f_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='tel',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='cof',
            new_name='codigo_orden_fabricacion',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='cp',
            new_name='codigo_proceso',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='f_fin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='f_inicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='nom_pro',
            new_name='nombre_proceso',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='ref',
            new_name='referencia',
        ),
    ]
