# Generated by Django 3.0.4 on 2020-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0003_auto_20200411_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default='01/01/1990'),
        ),
    ]
