# Generated by Django 3.0.4 on 2020-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0004_auto_20200429_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.DateField(default='01/01/1990'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_instalacion',
            field=models.DateField(default='01/01/1990'),
        ),
    ]
