# Generated by Django 3.0.4 on 2020-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0005_auto_20200429_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='fecha_fin',
            field=models.DateField(default='01/01/1990'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_inicio',
            field=models.DateField(default='01/01/1990'),
        ),
    ]
