# Generated by Django 3.0.4 on 2020-05-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0008_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
