# Generated by Django 3.0.4 on 2020-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0009_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
