# Generated by Django 3.0.4 on 2020-05-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0010_proceso_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer'), ('3', 'Otro')], default='Otro', max_length=6)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
