# Generated by Django 3.0.4 on 2020-05-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0011_novedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='genero',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otro')], default='Otro', max_length=9),
        ),
    ]
