# Generated by Django 3.0.4 on 2020-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0012_auto_20200517_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='genero',
            field=models.CharField(choices=[('mas', 'Masculino'), ('fem', 'Femenino'), ('otro', 'Otro')], default='Otro', max_length=9),
        ),
    ]
