# Generated by Django 3.0.4 on 2020-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduccion', '0013_auto_20200519_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='genero',
            field=models.CharField(choices=[('mas', 'Masculino'), ('fem', 'Femenino'), ('otro', 'Otro')], default='otro', max_length=9),
        ),
    ]
