# Generated by Django 3.0.4 on 2020-05-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField(default=666666666)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(default='01/01/1990')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField(default='01/01/1990')),
                ('fecha_instalacion', models.DateField(default='01/01/1990')),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('mas', 'Masculino'), ('fem', 'Femenino'), ('otro', 'Otro')], default='otro', max_length=9)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden_fabricacion', models.CharField(max_length=75)),
                ('codigo_proceso', models.CharField(max_length=75)),
                ('nombre_proceso', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=75)),
                ('fecha_inicio', models.DateField(default='01/01/1990')),
                ('fecha_fin', models.DateField(default='01/01/1990')),
                ('activo', models.BooleanField(default=False)),
                ('empleados', models.ManyToManyField(to='appProduccion.Empleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduccion.Equipo')),
            ],
        ),
    ]
